CREATE TYPE notification_type AS ENUM ('apply', 'download_resume');

CREATE TABLE IF NOT EXISTS notification
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type notification_type NOT NULL,
    sender_id INT NOT NULL,
    receiver_id INT NOT NULL,
    object_id INT NOT NULL,
    is_viewed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);