CREATE TABLE IF NOT EXISTS poll (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
    CONSTRAINT poll_name_length CHECK (LENGTH(name) <= 128) NOT NULL
);

-- Таблица для голосований
CREATE TABLE IF NOT EXISTS vote (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INT REFERENCES poll (id) ON DELETE CASCADE,
    user_id INT NOT NULL,
  role TEXT
    CONSTRAINT user_role CHECK (role IN ('applicant', 'employer')) NOT NULL,
  answer INT
    CONSTRAINT answer_value CHECK (answer BETWEEN 1 AND 5) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);

INSERT INTO poll (name)
VALUES ('Насколько вы удовлетворены удобством ResuMatch?');
