CREATE TABLE IF NOT EXISTS poll (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT
    CONSTRAINT poll_name_length CHECK (LENGTH(name) <= 128) NOT NULL
);


CREATE TABLE IF NOT EXISTS vote (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poll_id INT REFERENCES poll (id) ON DELETE CASCADE,
    user_id INT NOT NULL,
  role TEXT
    CONSTRAINT user_role CHECK (role IN ('applicant', 'employer')) NOT NULL,
  answer INT
    CONSTRAINT answer_value CHECK (answer BETWEEN 1 AND 5) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO poll (name)
VALUES ('Насколько вы удовлетворены удобром ResuMatch?');

INSERT INTO poll (name) VALUES
('Как вы оцениваете качество вакансий на ResuMatch?'),
('Насколько легко вам найти подходящих кандидатов?');


INSERT INTO vote (poll_id, user_id, role, answer) VALUES
  (1, 1, 'applicant', 5),
  (1, 2, 'applicant', 4),
  (1, 3, 'applicant', 3),
  (1, 4, 'applicant', 5),
  (1, 6, 'applicant', 2),
  (1, 1, 'employer', 4);


INSERT INTO vote (poll_id, user_id, role, answer) VALUES
  (2, 2, 'applicant', 1),
  (2, 3, 'applicant', 1),
  (2, 7, 'applicant', 2),
  (2, 8, 'applicant', 3),
  (2, 41, 'applicant', 5),
  (2, 1, 'employer', 5);


INSERT INTO vote (poll_id, user_id, role, answer) VALUES
  (3, 1, 'employer', 4),
  (3, 1, 'employer', 3);
