CREATE TABLE chat (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id INTEGER NOT NULL REFERENCES vacancy(id) ON DELETE CASCADE,
    resume_id INTEGER NOT NULL REFERENCES resume(id) ON DELETE CASCADE,
    applicant_id INTEGER NOT NULL REFERENCES applicant(id) ON DELETE CASCADE,
    employer_id INTEGER NOT NULL REFERENCES employer(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
--     UNIQUE (vacancy_id, resume_id, applicant_id, employer_id)
);

CREATE TABLE message (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INTEGER NOT NULL REFERENCES chat(id) ON DELETE CASCADE,
    sender_id INTEGER NOT NULL,
    from_applicant BOOLEAN NOT NULL,
    payload TEXT
    CONSTRAINT message_payload_length CHECK (LENGTH(payload) <= 1024) NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_chat_applicant ON chat(applicant_id);
CREATE INDEX idx_chat_employer ON chat(employer_id);
CREATE INDEX idx_message_chat ON message(chat_id);

CREATE OR REPLACE FUNCTION update_chat_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE chat
    SET updated_at = CURRENT_TIMESTAMP
    WHERE id = NEW.chat_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_chat_updated_at
    AFTER INSERT ON message
    FOR EACH ROW
EXECUTE FUNCTION update_chat_updated_at();