// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: poll.proto

package poll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string           `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	VoteData      *VotePollRequest `protobuf:"bytes,3,opt,name=vote_data,json=voteData,proto3" json:"vote_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_poll_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{0}
}

func (x *VoteRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *VoteRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *VoteRequest) GetVoteData() *VotePollRequest {
	if x != nil {
		return x.VoteData
	}
	return nil
}

type VotePollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        uint64                 `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Answer        uint64                 `protobuf:"varint,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VotePollRequest) Reset() {
	*x = VotePollRequest{}
	mi := &file_poll_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VotePollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VotePollRequest) ProtoMessage() {}

func (x *VotePollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VotePollRequest.ProtoReflect.Descriptor instead.
func (*VotePollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{1}
}

func (x *VotePollRequest) GetPollId() uint64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

func (x *VotePollRequest) GetAnswer() uint64 {
	if x != nil {
		return x.Answer
	}
	return 0
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Polls         []*PollStatsResponse   `protobuf:"bytes,1,rep,name=polls,proto3" json:"polls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_poll_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatsResponse) GetPolls() []*PollStatsResponse {
	if x != nil {
		return x.Polls
	}
	return nil
}

type PollStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        uint64                 `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Average       float64                `protobuf:"fixed64,2,opt,name=average,proto3" json:"average,omitempty"`
	Name          string       `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Stars         []*StarStats `protobuf:"bytes,4,rep,name=stars,proto3" json:"stars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollStatsResponse) Reset() {
	*x = PollStatsResponse{}
	mi := &file_poll_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollStatsResponse) ProtoMessage() {}

func (x *PollStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollStatsResponse.ProtoReflect.Descriptor instead.
func (*PollStatsResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{3}
}

func (x *PollStatsResponse) GetPollId() uint64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

func (x *PollStatsResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *PollStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PollStatsResponse) GetStars() []*StarStats {
	if x != nil {
		return x.Stars
	}
	return nil
}

type StarStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Star          uint64                 `protobuf:"varint,1,opt,name=star,proto3" json:"star,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarStats) Reset() {
	*x = StarStats{}
	mi := &file_poll_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarStats) ProtoMessage() {}

func (x *StarStats) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarStats.ProtoReflect.Descriptor instead.
func (*StarStats) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{4}
}

func (x *StarStats) GetStar() uint64 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *StarStats) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StarStats) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type GetNewPollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewPollRequest) Reset() {
	*x = GetNewPollRequest{}
	mi := &file_poll_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewPollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewPollRequest) ProtoMessage() {}

func (x *GetNewPollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewPollRequest.ProtoReflect.Descriptor instead.
func (*GetNewPollRequest) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{5}
}

func (x *GetNewPollRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetNewPollRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        uint64                 `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_poll_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_poll_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_poll_proto_rawDescGZIP(), []int{6}
}

func (x *PollResponse) GetPollId() uint64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

func (x *PollResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_poll_proto protoreflect.FileDescriptor

const file_poll_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"poll.proto\x12\x04poll\x1a\x1bgoogle/protobuf/empty.proto\"n\n" +
	"\vVoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x122\n" +
	"\tvote_data\x18\x03 \x01(\v2\x15.poll.VotePollRequestR\bvoteData\"B\n" +
	"\x0fVotePollRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\x04R\x06pollId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\x04R\x06answer\"A\n" +
	"\x10GetStatsResponse\x12-\n" +
	"\x05polls\x18\x01 \x03(\v2\x17.poll.PollStatsResponseR\x05polls\"\x81\x01\n" +
	"\x11PollStatsResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\x04R\x06pollId\x12\x18\n" +
	"\aaverage\x18\x02 \x01(\x01R\aaverage\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x05stars\x18\x04 \x03(\v2\x0f.poll.StarStatsR\x05stars\"W\n" +
	"\tStarStats\x12\x12\n" +
	"\x04star\x18\x01 \x01(\x04R\x04star\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"@\n" +
	"\x11GetNewPollRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\";\n" +
	"\fPollResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\x04R\x06pollId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xb7\x01\n" +
	"\vPollService\x121\n" +
	"\x04Vote\x12\x11.poll.VoteRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bGetStats\x12\x16.google.protobuf.Empty\x1a\x16.poll.GetStatsResponse\x129\n" +
	"\n" +
	"GetNewPoll\x12\x17.poll.GetNewPollRequest\x1a\x12.poll.PollResponseB\tZ\a./;pollb\x06proto3"

var (
	file_poll_proto_rawDescOnce sync.Once
	file_poll_proto_rawDescData []byte
)

func file_poll_proto_rawDescGZIP() []byte {
	file_poll_proto_rawDescOnce.Do(func() {
		file_poll_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_poll_proto_rawDesc), len(file_poll_proto_rawDesc)))
	})
	return file_poll_proto_rawDescData
}

var file_poll_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_poll_proto_goTypes = []any{
	(*VoteRequest)(nil),       // 0: poll.VoteRequest
	(*VotePollRequest)(nil),   // 1: poll.VotePollRequest
	(*GetStatsResponse)(nil),  // 2: poll.GetStatsResponse
	(*PollStatsResponse)(nil), // 3: poll.PollStatsResponse
	(*StarStats)(nil),         // 4: poll.StarStats
	(*GetNewPollRequest)(nil), // 5: poll.GetNewPollRequest
	(*PollResponse)(nil),      // 6: poll.PollResponse
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_poll_proto_depIdxs = []int32{
	1, // 0: poll.VoteRequest.vote_data:type_name -> poll.VotePollRequest
	3, // 1: poll.GetStatsResponse.polls:type_name -> poll.PollStatsResponse
	4, // 2: poll.PollStatsResponse.stars:type_name -> poll.StarStats
	0, // 3: poll.PollService.Vote:input_type -> poll.VoteRequest
	7, // 4: poll.PollService.GetStats:input_type -> google.protobuf.Empty
	5, // 5: poll.PollService.GetNewPoll:input_type -> poll.GetNewPollRequest
	7, // 6: poll.PollService.Vote:output_type -> google.protobuf.Empty
	2, // 7: poll.PollService.GetStats:output_type -> poll.GetStatsResponse
	6, // 8: poll.PollService.GetNewPoll:output_type -> poll.PollResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_poll_proto_init() }
func file_poll_proto_init() {
	if File_poll_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_poll_proto_rawDesc), len(file_poll_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_poll_proto_goTypes,
		DependencyIndexes: file_poll_proto_depIdxs,
		MessageInfos:      file_poll_proto_msgTypes,
	}.Build()
	File_poll_proto = out.File
	file_poll_proto_goTypes = nil
	file_poll_proto_depIdxs = nil
}
