// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson28c0c648DecodeResuMatchInternalEntityDto(in *jlexer.Lexer, out *ApplicantProfileUpdate) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "first_name":
			out.FirstName = string(in.String())
		case "last_name":
			out.LastName = string(in.String())
		case "middle_name":
			out.MiddleName = string(in.String())
		case "city":
			out.City = string(in.String())
		case "birth_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.BirthDate).UnmarshalJSON(data))
			}
		case "sex":
			out.Sex = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "quote":
			out.Quote = string(in.String())
		case "vk":
			out.Vk = string(in.String())
		case "telegram":
			out.Telegram = string(in.String())
		case "facebook":
			out.Facebook = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson28c0c648EncodeResuMatchInternalEntityDto(out *jwriter.Writer, in ApplicantProfileUpdate) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"middle_name\":"
		out.RawString(prefix)
		out.String(string(in.MiddleName))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.Raw((in.BirthDate).MarshalJSON())
	}
	{
		const prefix string = ",\"sex\":"
		out.RawString(prefix)
		out.String(string(in.Sex))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"quote\":"
		out.RawString(prefix)
		out.String(string(in.Quote))
	}
	{
		const prefix string = ",\"vk\":"
		out.RawString(prefix)
		out.String(string(in.Vk))
	}
	{
		const prefix string = ",\"telegram\":"
		out.RawString(prefix)
		out.String(string(in.Telegram))
	}
	{
		const prefix string = ",\"facebook\":"
		out.RawString(prefix)
		out.String(string(in.Facebook))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApplicantProfileUpdate) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson28c0c648EncodeResuMatchInternalEntityDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApplicantProfileUpdate) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson28c0c648EncodeResuMatchInternalEntityDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApplicantProfileUpdate) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson28c0c648DecodeResuMatchInternalEntityDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApplicantProfileUpdate) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson28c0c648DecodeResuMatchInternalEntityDto(l, v)
}
func easyjson28c0c648DecodeResuMatchInternalEntityDto1(in *jlexer.Lexer, out *ApplicantProfileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "first_name":
			out.FirstName = string(in.String())
		case "last_name":
			out.LastName = string(in.String())
		case "middle_name":
			out.MiddleName = string(in.String())
		case "city":
			out.City = string(in.String())
		case "birth_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.BirthDate).UnmarshalJSON(data))
			}
		case "sex":
			out.Sex = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "quote":
			out.Quote = string(in.String())
		case "vk":
			out.Vk = string(in.String())
		case "telegram":
			out.Telegram = string(in.String())
		case "facebook":
			out.Facebook = string(in.String())
		case "avatar_path":
			out.AvatarPath = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson28c0c648EncodeResuMatchInternalEntityDto1(out *jwriter.Writer, in ApplicantProfileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"middle_name\":"
		out.RawString(prefix)
		out.String(string(in.MiddleName))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.Raw((in.BirthDate).MarshalJSON())
	}
	{
		const prefix string = ",\"sex\":"
		out.RawString(prefix)
		out.String(string(in.Sex))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"quote\":"
		out.RawString(prefix)
		out.String(string(in.Quote))
	}
	{
		const prefix string = ",\"vk\":"
		out.RawString(prefix)
		out.String(string(in.Vk))
	}
	{
		const prefix string = ",\"telegram\":"
		out.RawString(prefix)
		out.String(string(in.Telegram))
	}
	{
		const prefix string = ",\"facebook\":"
		out.RawString(prefix)
		out.String(string(in.Facebook))
	}
	{
		const prefix string = ",\"avatar_path\":"
		out.RawString(prefix)
		out.String(string(in.AvatarPath))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApplicantProfileResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson28c0c648EncodeResuMatchInternalEntityDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApplicantProfileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson28c0c648EncodeResuMatchInternalEntityDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApplicantProfileResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson28c0c648DecodeResuMatchInternalEntityDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApplicantProfileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson28c0c648DecodeResuMatchInternalEntityDto1(l, v)
}
