// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entity

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9806e1DecodeResuMatchInternalEntity(in *jlexer.Lexer, out *NotificationsList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(NotificationsList, 0, 8)
			} else {
				*out = NotificationsList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *NotificationPreview
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(NotificationPreview)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9806e1EncodeResuMatchInternalEntity(out *jwriter.Writer, in NotificationsList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v NotificationsList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9806e1EncodeResuMatchInternalEntity(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NotificationsList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9806e1EncodeResuMatchInternalEntity(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NotificationsList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9806e1DecodeResuMatchInternalEntity(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NotificationsList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9806e1DecodeResuMatchInternalEntity(l, v)
}
func easyjson9806e1DecodeResuMatchInternalEntity1(in *jlexer.Lexer, out *NotificationPreview) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "type":
			out.Type = NotificationType(in.String())
		case "sender_id":
			out.SenderID = int(in.Int())
		case "receiver_id":
			out.ReceiverID = int(in.Int())
		case "object_id":
			out.ObjectID = int(in.Int())
		case "applicant_name":
			out.ApplicantName = string(in.String())
		case "employer_name":
			out.EmployerName = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "is_viewed":
			out.IsViewed = bool(in.Bool())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9806e1EncodeResuMatchInternalEntity1(out *jwriter.Writer, in NotificationPreview) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int(int(in.SenderID))
	}
	{
		const prefix string = ",\"receiver_id\":"
		out.RawString(prefix)
		out.Int(int(in.ReceiverID))
	}
	{
		const prefix string = ",\"object_id\":"
		out.RawString(prefix)
		out.Int(int(in.ObjectID))
	}
	{
		const prefix string = ",\"applicant_name\":"
		out.RawString(prefix)
		out.String(string(in.ApplicantName))
	}
	{
		const prefix string = ",\"employer_name\":"
		out.RawString(prefix)
		out.String(string(in.EmployerName))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"is_viewed\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsViewed))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NotificationPreview) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9806e1EncodeResuMatchInternalEntity1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NotificationPreview) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9806e1EncodeResuMatchInternalEntity1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NotificationPreview) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9806e1DecodeResuMatchInternalEntity1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NotificationPreview) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9806e1DecodeResuMatchInternalEntity1(l, v)
}
func easyjson9806e1DecodeResuMatchInternalEntity2(in *jlexer.Lexer, out *Notification) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "type":
			out.Type = NotificationType(in.String())
		case "sender_id":
			out.SenderID = int(in.Int())
		case "receiver_id":
			out.ReceiverID = int(in.Int())
		case "object_id":
			out.ObjectID = int(in.Int())
		case "is_viewed":
			out.IsViewed = bool(in.Bool())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9806e1EncodeResuMatchInternalEntity2(out *jwriter.Writer, in Notification) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"sender_id\":"
		out.RawString(prefix)
		out.Int(int(in.SenderID))
	}
	{
		const prefix string = ",\"receiver_id\":"
		out.RawString(prefix)
		out.Int(int(in.ReceiverID))
	}
	{
		const prefix string = ",\"object_id\":"
		out.RawString(prefix)
		out.Int(int(in.ObjectID))
	}
	{
		const prefix string = ",\"is_viewed\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsViewed))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Notification) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9806e1EncodeResuMatchInternalEntity2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Notification) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9806e1EncodeResuMatchInternalEntity2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Notification) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9806e1DecodeResuMatchInternalEntity2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Notification) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9806e1DecodeResuMatchInternalEntity2(l, v)
}
