// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: static.proto

package static

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileID) Reset() {
	*x = FileID{}
	mi := &file_static_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileID) ProtoMessage() {}

func (x *FileID) ProtoReflect() protoreflect.Message {
	mi := &file_static_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileID.ProtoReflect.Descriptor instead.
func (*FileID) Descriptor() ([]byte, []int) {
	return file_static_proto_rawDescGZIP(), []int{0}
}

func (x *FileID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StaticURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticURL) Reset() {
	*x = StaticURL{}
	mi := &file_static_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticURL) ProtoMessage() {}

func (x *StaticURL) ProtoReflect() protoreflect.Message {
	mi := &file_static_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticURL.ProtoReflect.Descriptor instead.
func (*StaticURL) Descriptor() ([]byte, []int) {
	return file_static_proto_rawDescGZIP(), []int{1}
}

func (x *StaticURL) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UploadStaticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStaticRequest) Reset() {
	*x = UploadStaticRequest{}
	mi := &file_static_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStaticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStaticRequest) ProtoMessage() {}

func (x *UploadStaticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_static_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStaticRequest.ProtoReflect.Descriptor instead.
func (*UploadStaticRequest) Descriptor() ([]byte, []int) {
	return file_static_proto_rawDescGZIP(), []int{2}
}

func (x *UploadStaticRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadStaticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadStaticResponse) Reset() {
	*x = UploadStaticResponse{}
	mi := &file_static_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadStaticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadStaticResponse) ProtoMessage() {}

func (x *UploadStaticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_static_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadStaticResponse.ProtoReflect.Descriptor instead.
func (*UploadStaticResponse) Descriptor() ([]byte, []int) {
	return file_static_proto_rawDescGZIP(), []int{3}
}

func (x *UploadStaticResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UploadStaticResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_static_proto protoreflect.FileDescriptor

const file_static_proto_rawDesc = "" +
	"\n" +
	"\fstatic.proto\x12\x06static\x1a\x1bgoogle/protobuf/empty.proto\"\x18\n" +
	"\x06FileID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1f\n" +
	"\tStaticURL\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\")\n" +
	"\x13UploadStaticRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\":\n" +
	"\x14UploadStaticResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path2\xc2\x01\n" +
	"\rStaticService\x12I\n" +
	"\fUploadStatic\x12\x1b.static.UploadStaticRequest\x1a\x1c.static.UploadStaticResponse\x12.\n" +
	"\tGetStatic\x12\x0e.static.FileID\x1a\x11.static.StaticURL\x126\n" +
	"\fDeleteStatic\x12\x0e.static.FileID\x1a\x16.google.protobuf.EmptyB\vZ\t./;staticb\x06proto3"

var (
	file_static_proto_rawDescOnce sync.Once
	file_static_proto_rawDescData []byte
)

func file_static_proto_rawDescGZIP() []byte {
	file_static_proto_rawDescOnce.Do(func() {
		file_static_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_static_proto_rawDesc), len(file_static_proto_rawDesc)))
	})
	return file_static_proto_rawDescData
}

var file_static_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_static_proto_goTypes = []any{
	(*FileID)(nil),               // 0: static.FileID
	(*StaticURL)(nil),            // 1: static.StaticURL
	(*UploadStaticRequest)(nil),  // 2: static.UploadStaticRequest
	(*UploadStaticResponse)(nil), // 3: static.UploadStaticResponse
	(*emptypb.Empty)(nil),        // 4: google.protobuf.Empty
}
var file_static_proto_depIdxs = []int32{
	2, // 0: static.StaticService.UploadStatic:input_type -> static.UploadStaticRequest
	0, // 1: static.StaticService.GetStatic:input_type -> static.FileID
	0, // 2: static.StaticService.DeleteStatic:input_type -> static.FileID
	3, // 3: static.StaticService.UploadStatic:output_type -> static.UploadStaticResponse
	1, // 4: static.StaticService.GetStatic:output_type -> static.StaticURL
	4, // 5: static.StaticService.DeleteStatic:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_static_proto_init() }
func file_static_proto_init() {
	if File_static_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_static_proto_rawDesc), len(file_static_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_static_proto_goTypes,
		DependencyIndexes: file_static_proto_depIdxs,
		MessageInfos:      file_static_proto_msgTypes,
	}.Build()
	File_static_proto = out.File
	file_static_proto_goTypes = nil
	file_static_proto_depIdxs = nil
}
