// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: static.proto

package static

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StaticService_UploadStatic_FullMethodName = "/static.StaticService/UploadStatic"
	StaticService_GetStatic_FullMethodName    = "/static.StaticService/GetStatic"
	StaticService_DeleteStatic_FullMethodName = "/static.StaticService/DeleteStatic"
)

// StaticServiceClient is the client API for StaticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StaticServiceClient interface {
	UploadStatic(ctx context.Context, in *UploadStaticRequest, opts ...grpc.CallOption) (*UploadStaticResponse, error)
	GetStatic(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*StaticURL, error)
	DeleteStatic(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type staticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStaticServiceClient(cc grpc.ClientConnInterface) StaticServiceClient {
	return &staticServiceClient{cc}
}

func (c *staticServiceClient) UploadStatic(ctx context.Context, in *UploadStaticRequest, opts ...grpc.CallOption) (*UploadStaticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadStaticResponse)
	err := c.cc.Invoke(ctx, StaticService_UploadStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticServiceClient) GetStatic(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*StaticURL, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StaticURL)
	err := c.cc.Invoke(ctx, StaticService_GetStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *staticServiceClient) DeleteStatic(ctx context.Context, in *FileID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, StaticService_DeleteStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StaticServiceServer is the server API for StaticService service.
// All implementations must embed UnimplementedStaticServiceServer
// for forward compatibility.
type StaticServiceServer interface {
	UploadStatic(context.Context, *UploadStaticRequest) (*UploadStaticResponse, error)
	GetStatic(context.Context, *FileID) (*StaticURL, error)
	DeleteStatic(context.Context, *FileID) (*emptypb.Empty, error)
	mustEmbedUnimplementedStaticServiceServer()
}

// UnimplementedStaticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStaticServiceServer struct{}

func (UnimplementedStaticServiceServer) UploadStatic(context.Context, *UploadStaticRequest) (*UploadStaticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadStatic not implemented")
}
func (UnimplementedStaticServiceServer) GetStatic(context.Context, *FileID) (*StaticURL, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatic not implemented")
}
func (UnimplementedStaticServiceServer) DeleteStatic(context.Context, *FileID) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStatic not implemented")
}
func (UnimplementedStaticServiceServer) mustEmbedUnimplementedStaticServiceServer() {}
func (UnimplementedStaticServiceServer) testEmbeddedByValue()                       {}

// UnsafeStaticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StaticServiceServer will
// result in compilation errors.
type UnsafeStaticServiceServer interface {
	mustEmbedUnimplementedStaticServiceServer()
}

func RegisterStaticServiceServer(s grpc.ServiceRegistrar, srv StaticServiceServer) {
	// If the following call pancis, it indicates UnimplementedStaticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StaticService_ServiceDesc, srv)
}

func _StaticService_UploadStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadStaticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServiceServer).UploadStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticService_UploadStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServiceServer).UploadStatic(ctx, req.(*UploadStaticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticService_GetStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServiceServer).GetStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticService_GetStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServiceServer).GetStatic(ctx, req.(*FileID))
	}
	return interceptor(ctx, in, info, handler)
}

func _StaticService_DeleteStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StaticServiceServer).DeleteStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StaticService_DeleteStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StaticServiceServer).DeleteStatic(ctx, req.(*FileID))
	}
	return interceptor(ctx, in, info, handler)
}

// StaticService_ServiceDesc is the grpc.ServiceDesc for StaticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StaticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "static.StaticService",
	HandlerType: (*StaticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadStatic",
			Handler:    _StaticService_UploadStatic_Handler,
		},
		{
			MethodName: "GetStatic",
			Handler:    _StaticService_GetStatic_Handler,
		},
		{
			MethodName: "DeleteStatic",
			Handler:    _StaticService_DeleteStatic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "static.proto",
}
