run:
  timeout: 5m

linters:
  enable:
    - govet  # стандартный анализатор Go
    - revive  # проверка стиля кода
    - errcheck  # проверяет, что ошибки не игнорируются
    - staticcheck  # выявляет потенциальные ошибки в коде
    - unused  # находит неиспользуемый код
    - ineffassign  # проверяет неиспользуемые переменные
    - gofmt  # проверяет форматирование кода
    - gocyclo  # оценивает сложность функций
    - unused  # удаляет ненужные части кода

issues:
  exclude:
    - _test\.go$  # игнорировать тестовые файлы
