// Code generated by MockGen. DO NOT EDIT.
// Source: ResuMatch/internal/repository (interfaces: StaticRepository)
//
// Generated by this command:
//
//	mockgen -package mock -destination internal/repository/mock/mock_static.go ResuMatch/internal/repository StaticRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	entity "ResuMatch/internal/entity"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStaticRepository is a mock of StaticRepository interface.
type MockStaticRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStaticRepositoryMockRecorder
	isgomock struct{}
}

// MockStaticRepositoryMockRecorder is the mock recorder for MockStaticRepository.
type MockStaticRepositoryMockRecorder struct {
	mock *MockStaticRepository
}

// NewMockStaticRepository creates a new mock instance.
func NewMockStaticRepository(ctrl *gomock.Controller) *MockStaticRepository {
	mock := &MockStaticRepository{ctrl: ctrl}
	mock.recorder = &MockStaticRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaticRepository) EXPECT() *MockStaticRepositoryMockRecorder {
	return m.recorder
}

// GetStatic mocks base method.
func (m *MockStaticRepository) GetStatic(ctx context.Context, id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatic", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatic indicates an expected call of GetStatic.
func (mr *MockStaticRepositoryMockRecorder) GetStatic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatic", reflect.TypeOf((*MockStaticRepository)(nil).GetStatic), ctx, id)
}

// UploadStatic mocks base method.
func (m *MockStaticRepository) UploadStatic(ctx context.Context, filePath, fileName string, data []byte) (*entity.Static, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadStatic", ctx, filePath, fileName, data)
	ret0, _ := ret[0].(*entity.Static)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadStatic indicates an expected call of UploadStatic.
func (mr *MockStaticRepositoryMockRecorder) UploadStatic(ctx, filePath, fileName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadStatic", reflect.TypeOf((*MockStaticRepository)(nil).UploadStatic), ctx, filePath, fileName, data)
}
